export { default as InfoSecPolicy } from "./InfoSecPolicy"
export { default as OnlinePurchasePolicy } from "./OnlinePurchasePolicy"
export { default as GeneralPolicy } from "./GeneralPolicy"
export { default as PaymentPolicy } from "./PaymentPolicy"
export { default as RefundPolicy } from "./RefundPolicy"
export { default as ComplaintPolicy } from "./ComplaintPolicy"